
#mysql数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo-user-service?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Shanghai
    username: root
    password: qwe123

  # redis配置
  redis:
    host: localhost
    port: 6379
    password: qwe123
    lettuce:
      pool:
        max-active: 10
        min-idle: 1
        max-idle: 10
        time-between-eviction-runs: 10s

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #用户查看mybatis-plus执行的sql语句

  #设置mybatis-plus的全局配置
#  global-config:
#    db-config:
#      table-prefix: t_ #可用来配置全局的实体类映射的表名前缀
#      id-type: auto #用于全局主键生成策略
